import type { Ticket } from "@/types/ticket";

export const seedTickets: Ticket[] = [
  {
    id: crypto.randomUUID(),
    tenant: "Jane Smith",
    unit: "KH – F1D4",
    body: "The dishwasher is leaking significantly from the bottom during the rinse cycle. Water pools on the kitchen floor and creates a slipping hazard.",
    createdAt: new Date("2025-11-15"),
    status: false,
  },
  {
    id: crypto.randomUUID(),
    tenant: "Robert Jones",
    unit: "KH – F3D2",
    body: "There is a persistent, loud dripping noise coming from inside the wall near the bathroom. It seems to be getting worse over time.",
    createdAt: new Date("2025-11-28"),
    status: false,
  },
  {
    id: crypto.randomUUID(),
    tenant: "Maria Rodriguez",
    unit: "KH – F5D1",
    body: "The main breaker for the living room and kitchen outlets trips constantly, even when only a few appliances are plugged in.",
    createdAt: new Date("2025-12-05"),
    status: false,
  },
  {
    id: crypto.randomUUID(),
    tenant: "John Doe",
    unit: "KH – F2D3",
    body: "The heating system is not working properly. The apartment remains cold even when the thermostat is set to the highest temperature.",
    createdAt: new Date("2025-12-10"),
    status: false,
  },
  {
    id: crypto.randomUUID(),
    tenant: "Alice Brown",
    unit: "KH – F4D1",
    body: "The kitchen sink faucet is loose and wobbly. It leaks water around the base whenever it is turned on.",
    createdAt: new Date("2025-12-12"),
    status: false,
  },
  {
    id: crypto.randomUUID(),
    tenant: "Michael Green",
    unit: "KH – F6D2",
    body: "The ceiling in the bedroom has developed a large crack, and pieces of plaster are starting to fall onto the floor.",
    createdAt: new Date("2025-12-15"),
    status: false,
  },
  {
    id: crypto.randomUUID(),
    tenant: "Emily White",
    unit: "KH – F7D3",
    body: "The refrigerator is not cooling properly. Food spoils quickly, and there is a strange humming noise coming from the back.",
    createdAt: new Date("2025-12-18"),
    status: false,
  },
  {
    id: crypto.randomUUID(),
    tenant: "David Black",
    unit: "KH – F8D4",
    body: "The bathroom exhaust fan is not working. The bathroom becomes very humid and mold is starting to grow on the walls.",
    createdAt: new Date("2025-12-20"),
    status: false,
  },
  {
    id: crypto.randomUUID(),
    tenant: "Sophia Gray",
    unit: "KH – F9D1",
    body: "The front door lock is jammed and difficult to open. It takes several attempts to unlock the door, which is a safety concern.",
    createdAt: new Date("2025-12-22"),
    status: false,
  },
  {
    id: crypto.randomUUID(),
    tenant: "Chris Blue",
    unit: "KH – F10D2",
    body: "The washing machine is making a loud banging noise during the spin cycle. It also vibrates excessively, causing it to move out of place.",
    createdAt: new Date("2025-12-25"),
    status: false,
  },
];
